title: Newbie Playground
description: It will be something amazing.
template:
  repo: newbie-playground-template
  name: newbie-playground
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
